version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - symfony-docker-php
    env_file:
      - .env
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9001:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - database
    networks:
      - symfony-docker-php
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - symfony-docker-php
    env_file:
      - .env
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - php
      - database
    links:
      - database
    networks:
      - symfony-docker-php
    env_file:
      - .env

networks:
  symfony-docker-php: